# Generated by Django 2.1 on 2018-09-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_product_orderserialno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='orderSerialNo',
        ),
        migrations.AddField(
            model_name='order',
            name='orderSerialNo',
            field=models.ManyToManyField(blank=True, to='api.OrderSerialNo'),
        ),
    ]
